import { ThemeConfig, BlockType, WeddingBlockData } from "./types";

export interface TemplateDefinition {
  id: string;
  name: string;
  slug: string;
  thumbnail: string;
  description: string;
  category: "luxury" | "minimal" | "romantic" | "editorial" | "traditional";
  tags: string[];
  defaultTheme: ThemeConfig;
  defaultBlocks: Array<{
    type: BlockType;
    order: number;
    enabled: boolean;
    title?: string;
    subtitle?: string;
    layout?: string;
    content: Record<string, any>;
  }>;
}

export const TEMPLATES: TemplateDefinition[] = [
  {
    id: "elegant-ivory",
    name: "Elegant Ivory",
    slug: "elegant-ivory",
    thumbnail: "https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80",
    description: "Nền kem ngà thanh lịch, typography serif quý phái, viền chỉ vàng kim tinh tế, phong cách quý tộc vượt thời gian.",
    category: "luxury",
    tags: ["Sang trọng", "Tone kem", "Serif", "Châu Âu"],
    defaultTheme: {
      id: "theme-ivory",
      name: "Ivory & Gold",
      primaryColor: "#2A2826",
      secondaryColor: "#7A7369",
      accentColor: "#C5A059",
      backgroundColor: "#FDFBF7",
      cardBackgroundColor: "#FFFFFF",
      textColor: "#2D2A26",
      mutedTextColor: "#827B73",
      borderColor: "#EADDC8",
      fontHeading: "'Playfair Display', serif",
      fontBody: "'Inter', sans-serif",
      fontScript: "'Alex Brush', cursive",
      borderRadius: "md",
      cardStyle: "bordered",
    },
    defaultBlocks: [
      {
        type: "hero",
        order: 1,
        enabled: true,
        title: "Save Our Date",
        subtitle: "Chúng mình sắp về chung một nhà",
        layout: "centered",
        content: {
          badge: "THE WEDDING CELEBRATION",
          quote: "Tình yêu là khi hai trái tim tìm thấy cùng một nhịp đập.",
          overlayOpacity: 35,
        },
      },
      {
        type: "couple",
        order: 2,
        enabled: true,
        title: "Cô Dâu & Chú Rể",
        subtitle: "Hai nửa yêu thương",
        layout: "cards",
        content: {},
      },
      {
        type: "countdown",
        order: 3,
        enabled: true,
        title: "Đếm Ngược Ngày Chung Đôi",
        subtitle: "Chỉ còn một chút thời gian nữa thôi",
        layout: "flip",
        content: {
          postWeddingMessage: "Cảm ơn bạn đã cùng chia sẻ khoảnh khắc tuyệt vời nhất cuộc đời chúng mình!",
        },
      },
      {
        type: "story",
        order: 4,
        enabled: true,
        title: "Câu Chuyện Tình Yêu",
        subtitle: "Hành trình từ người xa lạ đến bạn đời",
        layout: "timeline",
        content: {
          stories: [
            {
              id: "s1",
              year: "2021",
              title: "Lần Đầu Gặp Gỡ",
              description: "Một chiều thu Hà Nội dưới tán cây Hoàng Diệu, vô tình nhìn thấy ánh mắt ấy và biết rằng định mệnh đã an bài.",
              image: "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=600&q=80",
            },
            {
              id: "s2",
              year: "2023",
              title: "Lời Cầu Hôn Trong Mơ",
              description: "Giữa bãi biển hoàng hôn Phú Quốc, chiếc nhẫn được trao đi cùng lời hứa bên nhau trọn đời.",
              image: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=600&q=80",
            },
          ],
        },
      },
      {
        type: "events",
        order: 5,
        enabled: true,
        title: "Sự Kiện Cưới",
        subtitle: "Thời gian & địa điểm diễn ra các nghi lễ",
        layout: "cards",
        content: {},
      },
      {
        type: "gallery",
        order: 6,
        enabled: true,
        title: "Khoảnh Khắc Hạnh Phúc",
        subtitle: "Kỷ niệm trước ngày trọng đại",
        layout: "masonry",
        content: {
          layout: "masonry",
        },
      },
      {
        type: "map",
        order: 7,
        enabled: true,
        title: "Địa Điểm Tiệc Cưới",
        subtitle: "Rất hân hạnh được đón tiếp quý khách",
        layout: "card",
        content: {},
      },
      {
        type: "rsvp",
        order: 8,
        enabled: true,
        title: "Xác Nhận Tham Dự (RSVP)",
        subtitle: "Sự hiện diện của bạn là niềm vinh hạnh cho gia đình chúng mình",
        layout: "standard",
        content: {
          deadline: "Vui lòng xác nhận trước 5 ngày diễn ra tiệc",
          enableGuestCount: true,
          enableSideChoice: true,
        },
      },
      {
        type: "guestbook",
        order: 9,
        enabled: true,
        title: "Sổ Lưu Bút Chúc Mừng",
        subtitle: "Hãy để lại những lời chúc thân thương nhất",
        layout: "wall",
        content: {
          placeholder: "Gửi lời chúc hạnh phúc đến cô dâu & chú rể...",
        },
      },
      {
        type: "thank_you",
        order: 10,
        enabled: true,
        title: "Trân Trọng Cảm Ơn",
        subtitle: "Thank You",
        layout: "centered",
        content: {
          message: "Sự hiện diện và lời chúc phúc của quý khách là món quà quý giá nhất đối với chúng mình trong ngày trọng đại này.",
        },
      },
    ],
  },
  {
    id: "burgundy-wedding",
    name: "Burgundy Grandeur",
    slug: "burgundy-wedding",
    thumbnail: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=800&q=80",
    description: "Sắc đỏ burgundy nồng nàn quý phái kết hợp cùng điểm nhấn vàng kim hoàng gia, ánh nến lung linh và huyền ảo.",
    category: "luxury",
    tags: ["Đỏ Burgundy", "Hoàng gia", "Tiệc tối", "Sang trọng"],
    defaultTheme: {
      id: "theme-burgundy",
      name: "Burgundy & Gold Royal",
      primaryColor: "#E5C158",
      secondaryColor: "#C99A45",
      accentColor: "#E5C158",
      backgroundColor: "#2C0B12",
      cardBackgroundColor: "#3E121C",
      textColor: "#F9F3EA",
      mutedTextColor: "#D6B8BE",
      borderColor: "#681F2F",
      fontHeading: "'Cinzel', serif",
      fontBody: "'Montserrat', sans-serif",
      fontScript: "'Alex Brush', cursive",
      borderRadius: "sm",
      cardStyle: "bordered",
    },
    defaultBlocks: [
      {
        type: "hero",
        order: 1,
        enabled: true,
        title: "Royal Wedding",
        subtitle: "Lễ Thành Hôn Trọng Đại",
        layout: "editorial",
        content: {
          badge: "CORONATION OF LOVE",
          quote: "Tình yêu là điều kỳ diệu nhất mà vũ trụ ban tặng.",
          overlayOpacity: 45,
        },
      },
      {
        type: "couple",
        order: 2,
        enabled: true,
        title: "Groom & Bride",
        subtitle: "Cặp Đôi Hoàng Gia",
        layout: "cards",
        content: {},
      },
      {
        type: "countdown",
        order: 3,
        enabled: true,
        title: "Thời Khắc Linh Thiêng",
        subtitle: "Đếm ngược đến giờ lành",
        layout: "boxes",
        content: {},
      },
      {
        type: "story",
        order: 4,
        enabled: true,
        title: "Chương Tình Yêu",
        subtitle: "Từng cột mốc son sắt",
        layout: "timeline",
        content: { stories: [] },
      },
      {
        type: "events",
        order: 5,
        enabled: true,
        title: "Nghi Lễ & Dạ Tiệc",
        subtitle: "Trân trọng kính mời quý khách",
        layout: "cards",
        content: {},
      },
      {
        type: "gallery",
        order: 6,
        enabled: true,
        title: "Album Cưới Hoàng Gia",
        subtitle: "Vẻ đẹp vượt thời gian",
        layout: "grid-3",
        content: { layout: "grid-3" },
      },
      {
        type: "map",
        order: 7,
        enabled: true,
        title: "Cung Điện Tiệc Cưới",
        subtitle: "Grand Ballroom",
        layout: "card",
        content: {},
      },
      {
        type: "rsvp",
        order: 8,
        enabled: true,
        title: "Phản Hồi Tham Dự (RSVP)",
        subtitle: "Xin vui lòng xác nhận để chúng mình chu đáo đón tiếp",
        layout: "standard",
        content: {},
      },
      {
        type: "guestbook",
        order: 9,
        enabled: true,
        title: "Lời Chúc Phúc Kim Cương",
        subtitle: "Ghi dấu kỷ niệm đáng nhớ",
        layout: "wall",
        content: {},
      },
      {
        type: "thank_you",
        order: 10,
        enabled: true,
        title: "Tri Ân Quý Khách",
        subtitle: "With Deepest Gratitude",
        layout: "centered",
        content: {
          message: "Kính chúc quý khách và gia đình luôn dồi dào sức khỏe, may mắn và ngập tràn hạnh phúc!",
        },
      },
    ],
  },
  {
    id: "sage-minimal",
    name: "Sage Minimalist",
    slug: "sage-minimal",
    thumbnail: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&q=80",
    description: "Sắc xanh xô thơm tự nhiên, nền trắng kem tinh khiết, phong cách tối giản thanh khiết cho đám cưới ngoài trời.",
    category: "minimal",
    tags: ["Xanh Sage", "Tối giản", "Botanical", "Hiện đại"],
    defaultTheme: {
      id: "theme-sage",
      name: "Sage Green & Warm Cream",
      primaryColor: "#4B5E4F",
      secondaryColor: "#758A79",
      accentColor: "#67826E",
      backgroundColor: "#F7F9F7",
      cardBackgroundColor: "#FFFFFF",
      textColor: "#2B352E",
      mutedTextColor: "#6B7C6E",
      borderColor: "#DCE5DC",
      fontHeading: "'Cormorant Garamond', serif",
      fontBody: "'Plus Jakarta Sans', sans-serif",
      fontScript: "'Alex Brush', cursive",
      borderRadius: "lg",
      cardStyle: "clean",
    },
    defaultBlocks: [
      {
        type: "hero",
        order: 1,
        enabled: true,
        title: "Tình Yêu Thuần Khiết",
        subtitle: "Ngày chúng ta chung một mái nhà",
        layout: "centered",
        content: {
          badge: "WE ARE GETTING MARRIED",
          quote: "Hạnh phúc đơn giản là cùng nhau già đi.",
          overlayOpacity: 25,
        },
      },
      {
        type: "couple",
        order: 2,
        enabled: true,
        title: "Nhân Vật Chính",
        subtitle: "Minh & Linh",
        layout: "clean",
        content: {},
      },
      {
        type: "countdown",
        order: 3,
        enabled: true,
        title: "Thời Gian Chờ Đợi",
        subtitle: "Mỗi giây trôi qua đều là niềm mong đợi",
        layout: "minimal",
        content: {},
      },
      {
        type: "story",
        order: 4,
        enabled: true,
        title: "Từng Bước Đi Cùng Nhau",
        subtitle: "Chuyện tình xanh mát như tán lá",
        layout: "timeline",
        content: { stories: [] },
      },
      {
        type: "events",
        order: 5,
        enabled: true,
        title: "Chương Trình Tiệc",
        subtitle: "Những khoảnh khắc không thể bỏ lỡ",
        layout: "clean",
        content: {},
      },
      {
        type: "gallery",
        order: 6,
        enabled: true,
        title: "Bộ Ảnh Kỷ Niệm (Polaroid)",
        subtitle: "Chạm vào ảnh để rút xem từng tấm",
        layout: "polaroid-stack",
        content: { layout: "polaroid-stack" },
      },
      {
        type: "map",
        order: 7,
        enabled: true,
        title: "Chỉ Dẫn Đường Đi",
        subtitle: "Khu vườn ngoài trời xanh mát",
        layout: "clean",
        content: {},
      },
      {
        type: "rsvp",
        order: 8,
        enabled: true,
        title: "Gửi Phản Hồi",
        subtitle: "Bạn sẽ đến chung vui cùng chúng mình chứ?",
        layout: "clean",
        content: {},
      },
      {
        type: "guestbook",
        order: 9,
        enabled: true,
        title: "Góc Nhỏ Lưu Bút",
        subtitle: "Lời chúc từ những người bạn thân thương",
        layout: "clean",
        content: {},
      },
      {
        type: "thank_you",
        order: 10,
        enabled: true,
        title: "Lời Cảm Ơn Chân Thành",
        subtitle: "With Love",
        layout: "centered",
        content: {
          message: "Cảm ơn vì đã luôn yêu thương, đồng hành và là một phần không thể thiếu trong câu chuyện của chúng mình.",
        },
      },
    ],
  },
  {
    id: "editorial-magazine",
    name: "Editorial Vogue",
    slug: "editorial-magazine",
    thumbnail: "https://images.unsplash.com/photo-1545232979-8bf68ee9b1af?w=800&q=80",
    description: "Phong cách bìa tạp chí thời trang cao cấp, typography serif ngoại cỡ sắc nét, bố cục nghệ thuật phá cách.",
    category: "editorial",
    tags: ["Tạp chí", "Editorial", "Thời trang", "Phá cách"],
    defaultTheme: {
      id: "theme-editorial",
      name: "Monochrome & High Editorial",
      primaryColor: "#0D0D0D",
      secondaryColor: "#404040",
      accentColor: "#A38655",
      backgroundColor: "#F4F3EF",
      cardBackgroundColor: "#FFFFFF",
      textColor: "#171717",
      mutedTextColor: "#737373",
      borderColor: "#E5E4DE",
      fontHeading: "'Playfair Display', serif",
      fontBody: "'Montserrat', sans-serif",
      fontScript: "'Alex Brush', cursive",
      borderRadius: "none",
      cardStyle: "clean",
    },
    defaultBlocks: [
      {
        type: "hero",
        order: 1,
        enabled: true,
        title: "VOGUE WEDDING ISSUE",
        subtitle: "Special Edition — Love in Full Bloom",
        layout: "magazine",
        content: {
          badge: "VOL. 2026 • EXCLUSIVE",
          quote: "Fashion fades, only love remains eternal.",
          overlayOpacity: 20,
        },
      },
      {
        type: "couple",
        order: 2,
        enabled: true,
        title: "The Protagonists",
        subtitle: "Nhân vật trang bìa",
        layout: "editorial",
        content: {},
      },
      {
        type: "countdown",
        order: 3,
        enabled: true,
        title: "Counting Down The Seconds",
        subtitle: "Showtime is coming",
        layout: "flip",
        content: {},
      },
      {
        type: "story",
        order: 4,
        enabled: true,
        title: "Behind The Scenes",
        subtitle: "Hành trình yêu như một cuốn phim",
        layout: "timeline",
        content: { stories: [] },
      },
      {
        type: "events",
        order: 5,
        enabled: true,
        title: "Event Itinerary",
        subtitle: "Lịch trình biểu diễn & đón khách",
        layout: "editorial",
        content: {},
      },
      {
        type: "gallery",
        order: 6,
        enabled: true,
        title: "Editorial Film Reel 35mm",
        subtitle: "Cuộn phim điện ảnh tự động trôi mượt mà",
        layout: "filmstrip",
        content: { layout: "filmstrip" },
      },
      {
        type: "map",
        order: 7,
        enabled: true,
        title: "Venue & Access",
        subtitle: "Chỉ dẫn lối vào thảm đỏ tiệc cưới",
        layout: "card",
        content: {},
      },
      {
        type: "rsvp",
        order: 8,
        enabled: true,
        title: "RSVP Invitation",
        subtitle: "Please confirm your VIP attendance",
        layout: "standard",
        content: {},
      },
      {
        type: "guestbook",
        order: 9,
        enabled: true,
        title: "Words of Love",
        subtitle: "Gửi những tâm tình đẹp đẽ nhất",
        layout: "wall",
        content: {},
      },
      {
        type: "thank_you",
        order: 10,
        enabled: true,
        title: "Merci Beaucoup",
        subtitle: "Thank You",
        layout: "centered",
        content: {
          message: "Thank you for being part of our special beginning. Forever grateful.",
        },
      },
    ],
  },
  {
    id: "traditional-luxury",
    name: "Traditional Vietnamese Luxury",
    slug: "traditional-luxury",
    thumbnail: "https://images.unsplash.com/photo-1532712938310-34cb3982ef74?w=800&q=80",
    description: "Đỏ son may mắn, nhung vàng hoàng gia phối hoa văn Song Hỷ tinh xảo, tôn vinh đạo hiếu và nét đẹp cưới Việt Nam hiện đại.",
    category: "traditional",
    tags: ["Truyền thống", "Song Hỷ", "Đỏ son", "Gia tiên"],
    defaultTheme: {
      id: "theme-traditional",
      name: "Crimson & Imperial Gold",
      primaryColor: "#A61C2C",
      secondaryColor: "#80121F",
      accentColor: "#D4AF37",
      backgroundColor: "#FCF8F5",
      cardBackgroundColor: "#FFFFFF",
      textColor: "#2B191B",
      mutedTextColor: "#856B6E",
      borderColor: "#F0DDD2",
      fontHeading: "'Playfair Display', serif",
      fontBody: "'Plus Jakarta Sans', sans-serif",
      fontScript: "'Alex Brush', cursive",
      borderRadius: "md",
      cardStyle: "bordered",
    },
    defaultBlocks: [
      {
        type: "hero",
        order: 1,
        enabled: true,
        title: "Trăm Năm Tình Viên Mãn",
        subtitle: "Lễ Vu Quy & Lễ Thành Hôn",
        layout: "traditional",
        content: {
          badge: "囍 TRĂM NĂM HẠNH PHÚC 囍",
          quote: "Duyên ba sinh hẹn ước, nghĩa trọn đời phu thê.",
          overlayOpacity: 35,
        },
      },
      {
        type: "family",
        order: 2,
        enabled: true,
        title: "Hai Họ Thông Gia",
        subtitle: "Kính báo tin mừng",
        layout: "standard",
        content: {
          title: "Đại Diện Hai Họ",
        },
      },
      {
        type: "couple",
        order: 3,
        enabled: true,
        title: "Tân Lang & Tân Nương",
        subtitle: "Xứng lứa vừa đôi",
        layout: "cards",
        content: {},
      },
      {
        type: "countdown",
        order: 4,
        enabled: true,
        title: "Ngày Lành Tháng Tốt",
        subtitle: "Thời khắc nên duyên vợ chồng",
        layout: "boxes",
        content: {},
      },
      {
        type: "events",
        order: 5,
        enabled: true,
        title: "Nghi Lễ Gia Tiên & Tiệc Mừng",
        subtitle: "Chương trình chi tiết",
        layout: "cards",
        content: {},
      },
      {
        type: "gallery",
        order: 6,
        enabled: true,
        title: "Album Áo Dài & Hạnh Phúc",
        subtitle: "Ghi dấu ngày sum vầy",
        layout: "grid-2",
        content: { layout: "grid-2" },
      },
      {
        type: "map",
        order: 7,
        enabled: true,
        title: "Địa Chỉ Nhà Gái & Nhà Trai",
        subtitle: "Kính mời quý khách tới chung vui",
        layout: "card",
        content: {},
      },
      {
        type: "rsvp",
        order: 8,
        enabled: true,
        title: "Phúc Đáp Thiệp Mừng (RSVP)",
        subtitle: "Sự hiện diện của quý khách là niềm vinh hạnh cho gia đình",
        layout: "standard",
        content: {},
      },
      {
        type: "guestbook",
        order: 9,
        enabled: true,
        title: "Gửi Lời Chúc Phúc",
        subtitle: "Mừng duyên đôi lứa trăm năm bền chặt",
        layout: "wall",
        content: {},
      },
      {
        type: "thank_you",
        order: 10,
        enabled: true,
        title: "Chân Thành Cảm Tạ",
        subtitle: "Gia đình hai họ đồng cảm tạ",
        layout: "centered",
        content: {
          message: "Gia đình hai bên xin chân thành cảm ơn quý cụ, quý bà, quý cô chú bác cùng toàn thể anh chị em bạn bè đã đến chung vui và chúc phúc cho hai cháu!",
        },
      },
    ],
  },
];
